general:
  kubeConfigFileCredentialsId: 'kube1'
steps:
  kubernetesDeploy:
    deployTool: 'helm3'
    chartPath: 'helm-charts/charts/demo'
    deploymentName: 'demo'

  helmExecute:
    chartPath: helm-charts/charts/demo
