@Library('piper-lib-os') _
node() {

    stage('prepare') {
        checkout scm
        setupCommonPipelineEnvironment script:this
    }

    stage("Lint") {

    }

    stage("Install & Test") {

    }

    stage("Package Charts") {

    }
    
    stage("Push Charts to Chart Repo") {

    }

}
