@Library('piper-lib-os') _
node() {

    stage('prepare') {
        checkout scm
        setupCommonPipelineEnvironment script:this
    }

    stage("Lint") {
        helmExecute script: this

    }

    stage("Install & Test") {
        helmExecute script: this

    }

    stage("Package Charts") {
        helmExecute script: this

    }

    stage("Push Charts to Chart Repo") {
        helmExecute script: this

    }

}
