@Library('piper-lib-os') _
node() {

    stage('prepare') {
        checkout scm
        setupCommonPipelineEnvironment script:this
    }

    stage("Lint") {
        helmExecute script: this, helmCommand: 'lint'
    }

    stage("Install & Test") {
        helmExecute script: this, helmCommand: 'dependency', dependency: 'update', chartPath: 'helm-charts/charts/demo'
        helmExecute script: this, helmCommand: 'install', chartPath: 'helm-charts/charts/demo'
        helmExecute script: this, helmCommand: 'test'
        helmExecute script: this, helmCommand: 'uninstall'
    }

    stage("Package Charts") {
        /* kubernetesDeploy script: this */
        /* kubernetesDeploy script: this, deployTool: 'helm3', chartPath: 'myChart', deploymentName: 'myRelease', image: 'nginx', containerRegistryUrl: 'https://docker.io' */

    }

    stage("Push Charts to Chart Repo") {

    }

}
